title = "Dimitria Eleftherios"
baseURL = "http://hugo.dimitriae.com"
languageCode = "en-us"
theme = "gohugo-theme-ananke"
css = "/css/style.css"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = "https://www.facebook.com/dimitria.eleftherios"
  twitter = ""
  instagram = "https://www.instagram.com/dimitriae/"
  youtube = ""
  github = "https://github.com/dimitriae"
  linkedin = "https://www.linkedin.com/in/dimitriae/"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/pronto.jpg"
